# Generated by Django 5.1.3 on 2024-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenaApp', '0003_alter_calendar_end_time_alter_calendar_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('menstruation', 'Menstruation'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], max_length=50)),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('symptoms', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
