# Generated by Django 5.1.3 on 2024-11-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenaApp', '0004_cyclephase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CyclePhase',
            new_name='CyclePhases',
        ),
    ]
