# Generated by Django 5.1.3 on 2024-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenaApp', '0007_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclephase',
            name='mood',
            field=models.TextField(default='no mood yet'),
            preserve_default=False,
        ),
    ]
