# Generated by Django 5.1.3 on 2024-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenaApp', '0009_remove_calendar_end_time_alter_calendar_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='day',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='month',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='year',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
